default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [ '--skip-string-normalization', '--line-length', '79' ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ '--profile', 'black', '--filter-files', '--line-length', '79' ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        exclude: migrations/
        language: python
        types: [ python ]

#  - repo: local
#    hooks:
#      - id: django-test
#        name: django-test
#        entry: python ./backend/manage.py test ./backend/
#        language: system
#        pass_filenames: false
