# Generated by Django 3.2.19 on 2023-08-29 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания задачи')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала выполнения задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('created', 'Задача создана'), ('in_progress', 'В процессе выполнения'), ('sent_for_review', 'Отправлена на проверку'), ('completed', 'Принята и выполнена'), ('returned_for_revision', 'Возвращена на доработку')], default='created', max_length=21, verbose_name='Статус задачи')),
                ('assignees', models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные пользователи')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('-creation_date',),
            },
        ),
    ]
