# Generated by Django 3.2.19 on 2023-08-23 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.TextField(verbose_name='Название задачи')),
                ('task_description', models.TextField(verbose_name='Описание задачи')),
                ('task_date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения задачи')),
                ('task_date_finish', models.DateField(verbose_name='Плановая дата завершения задачи')),
                ('task_status', models.CharField(choices=[(None, '(Статус задачи не определён)'), ('Задача завершена', 'Task Closed'), ('Задача назначена', 'Task Delegated'), ('Задача принята исполнителем', 'Task Accepted'), ('Задача выполнена исполнителем', 'Task Finished')], max_length=29, verbose_name='Текущий статус задачи')),
                ('employee_user', models.ForeignKey(default='deleted_user', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='accepted_tasks', to=settings.AUTH_USER_MODEL)),
                ('team_lead_user', models.ForeignKey(default='deleted_user', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='delegated_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
