# Generated by Django 3.2.19 on 2023-09-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
