# Generated by Django 3.2.19 on 2023-09-28 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0004_task_is_overdue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={
                'verbose_name': 'Задачу',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
