# Generated by Django 3.2.19 on 2023-10-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ux_ui', 'UX_UI'), ('qa', 'QA'), ('other', 'Other')], default='other', max_length=10, verbose_name='Подразделение'),
        ),
    ]
