# Generated by Django 3.2.19 on 2023-09-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.TextField(
                default=1, verbose_name='Заголовок новости'
            ),
            preserve_default=False,
        ),
    ]
