# Generated by Django 3.2.19 on 2023-08-05 16:29

from django.db import migrations, models
import django.utils.timezone
import users.models
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, help_text='Введите имя пользователя', max_length=255, unique=True, validators=[users.validators.validate_username], verbose_name='Ник-нейм')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', upload_to='users/%Y/%m/%d', verbose_name='Изображение')),
                ('email', models.EmailField(help_text='Введите адрес электронной почты', max_length=255, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=255, verbose_name='Фамилия')),
                ('second_name', models.CharField(help_text='Введите ваш отчество', max_length=255, verbose_name='Отчество')),
                ('birthday', models.DateField(help_text='Введите вашу дату рождения', verbose_name='Дата рождения')),
                ('password', models.CharField(help_text='Введите пароль', max_length=255, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('teamleader', 'Тимлид'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Роль')),
                ('contact', models.TextField(help_text='Введите список ваших доступных контактов', verbose_name='Контакты')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь персоналом')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен ли пользователь')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('username',),
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
