# Generated by Django 3.2.19 on 2023-08-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskill',
            name='name',
            field=models.CharField(help_text='Введите профессиоанльный навык/хардскилл', max_length=255, unique=True, verbose_name='Хардскилл'),
        ),
    ]
