# Generated by Django 3.2.19 on 2023-08-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=1, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='junior', max_length=6, verbose_name='Уровень должности'),
        ),
    ]
