# Generated by Django 3.2.19 on 2023-08-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.TextField(blank=True, help_text='Введите список ваших доступных контактов', verbose_name='Контакты'),
        ),
    ]
