# Generated by Django 3.2.19 on 2023-08-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bonus',
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
