# Generated by Django 3.2.19 on 2023-08-27 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230825_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите профессиоанльный навык/хардскилл', max_length=255, verbose_name='Хардскилл')),
            ],
            options={
                'verbose_name': 'Хардскилл',
                'verbose_name_plural': 'Хардскиллы',
            },
        ),
        migrations.CreateModel(
            name='UserHardskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hardskill', verbose_name='Хард скилл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hardskill', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профессиональный навык пользователя',
                'verbose_name_plural': 'Профессиональные навыки пользователя',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='hardskills',
            field=models.ManyToManyField(through='users.UserHardskill', to='users.Hardskill'),
        ),
        migrations.AddConstraint(
            model_name='userhardskill',
            constraint=models.UniqueConstraint(fields=('user', 'hardskill'), name='unique hardskill for user'),
        ),
    ]
