# Generated by Django 3.2.19 on 2023-08-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_hardskill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
