# Generated by Django 3.2.19 on 2023-08-07 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230806_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=255, verbose_name='Название KPI')),
                ('kpi_category', models.CharField(max_length=255, verbose_name='Категория KPI')),
                ('target', models.IntegerField(verbose_name='Целовой показатель KPI')),
                ('actual', models.IntegerField(verbose_name='Актуальный показатель KPI')),
                ('date', models.DateField(verbose_name='Дата выполнения задания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI показатель',
                'verbose_name_plural': 'KPI показатели',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='users.userrating', verbose_name='Рейтинг работника'),
        ),
    ]
