# Generated by Django 3.2.19 on 2023-08-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230817_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedemail',
            options={'verbose_name': 'Разрешенные email', 'verbose_name_plural': 'Разрешенные email'},
        ),
    ]
