# Generated by Django 3.2.19 on 2023-09-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230831_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='Введите вашу дату рождения', verbose_name='Дата рождения'),
        ),
    ]
