# Generated by Django 3.2.19 on 2023-09-23 14:18

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20230914_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(
                blank=True,
                choices=[
                    ('Backend', 'Backend'),
                    ('Frontend', 'Frontend'),
                    ('UX_UI', 'Ux Ui'),
                    ('QA', 'Qa'),
                    ('None', 'None'),
                ],
                default='None',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users_department',
                to='users.department',
                verbose_name='Подразделение',
            ),
        ),
    ]
