# Generated by Django 3.2.19 on 2023-09-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(
                choices=[
                    ('Backend', 'Backend'),
                    ('Frontend', 'Frontend'),
                    ('UX_UI', 'Ux Ui'),
                    ('QA', 'Qa'),
                    ('None', 'None'),
                ],
                default='None',
                max_length=8,
                verbose_name='Подразделение',
            ),
        ),
    ]
