# Generated by Django 3.2.19 on 2023-09-28 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
