# Generated by Django 3.2.19 on 2023-10-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('users', '0008_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_department', to='department.department', verbose_name='Подразделение'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
