# Generated by Django 3.2.19 on 2023-09-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_contact_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='platform',
            new_name='contact_type',
        ),
    ]
