# Generated by Django 3.2.22 on 2023-11-09 16:39

import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231010_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='general_experience',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Общий стаж'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Рабочий стаж в команде'),
        ),
    ]
