# Generated by Django 3.2.19 on 2023-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_platform_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='user_contacts', through='users.UserContact', to='users.Contact'),
        ),
    ]
