# Generated by Django 3.2.22 on 2023-12-10 08:35

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20231109_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аккаунт github'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аккаунт linkedin'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аккаунт telegram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
