# Generated by Django 3.2.19 on 2023-09-11 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='value',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ценность'),
        ),
    ]
