# Generated by Django 3.2.19 on 2023-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_achievement_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
