name: Django-app workflow

on: [push]

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3 
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push to Docker Hub
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/motivation_system
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Создание файла docker-compose.yaml
            cat <<EOF > /root/dev/docker-compose.yml
            version: '3.8'
            services:
              db:
                image: postgres:13.0-alpine
                volumes:
                  - /var/lib/postgresql/data/
                env_file:
                  - /root/dev/.env
              web:
                image: ${{ secrets.DOCKER_USERNAME }}/motivation_system
                restart: always
                volumes:
                  - static_value:/app/static/
                  - media_value:/app/media/
                depends_on:
                  - db
                env_file:
                  - /root/dev/.env
            volumes:
              static_value:
              media_value:
              postgres_data:
            EOF
  
            # Создание файла конфигурации Nginx
            cat <<EOF > /root/dev/nginx.conf
            server {
                listen 80;
                server_name 185.41.163.109;
  
                location /static/ {
                    alias /var/html/static/;
                }
                location /media/ {
                    alias /var/html/media/;
                }
                location / {
                    proxy_pass http://web:8000;
                }
            }
            EOF
  
            # Другие команды развертывания
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/motivation_system
            sudo docker-compose -f /root/dev/docker-compose.yml up -d
            sudo docker-compose -f /root/dev/docker-compose.yml exec -T web python manage.py collectstatic --no-input
            sudo docker-compose -f /root/dev/docker-compose.yml exec -T web python manage.py makemigrations
            sudo docker-compose -f /root/dev/docker-compose.yml exec -T web python manage.py migrate
  
